# Generated by Django 5.2.17 on 2026-10-04 12:45

import adgang.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=adgang.models.generate_token, editable=False, max_length=64, unique=True)),
                ('label', models.CharField(help_text='Hvem invitationen er til. Kun til dit eget overblik.', max_length=100, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('expires_at', models.DateTimeField(default=adgang.models.default_expiry, verbose_name='Udløber')),
                ('revoked', models.BooleanField(default=False, help_text='Sæt flueben for at gøre linket ubrugeligt uden at slette det.', verbose_name='Tilbagekaldt')),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Brugt')),
                ('accepted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitation', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitationer',
                'ordering': ['-created_at'],
            },
        ),
    ]
