# Generated by Django 4.2.30 on 2026-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Same as start date for a single-day trip.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
