# Generated by Django 5.2.17 on 2026-08-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booker',
            field=models.CharField(choices=[('person_1', 'Person 1'), ('person_2', 'Person 2'), ('person_3', 'Person 3'), ('person_4', 'Person 4'), ('person_5', 'Person 5'), ('person_6', 'Person 6')], default='person_1', max_length=20, verbose_name='Booker'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(help_text='Same as start date for a single-day trip.', verbose_name='Slutdato'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Noter'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(verbose_name='Startdato'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
    ]
