# Generated by Django 5.2.17 on 2026-08-19 16:02
#
# 0002 converted start_date/end_date from DateField to DateTimeField. On
# SQLite that rebuilds the table without reformatting existing values, so
# rows written before 0002 keep a bare "YYYY-MM-DD" string instead of a full
# datetime. Re-saving each row forces Django to write it back out in proper
# datetime form.

from django.db import migrations


def normalize_datetime_strings(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")
    for booking in Booking.objects.all():
        Booking.objects.filter(pk=booking.pk).update(
            start_date=booking.start_date,
            end_date=booking.end_date,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_booker_alter_booking_end_date_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_datetime_strings, migrations.RunPython.noop),
    ]
