# Generated by Django 5.2.17 on 2026-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_fix_datetime_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='series_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booker',
            field=models.CharField(choices=[('person_1', 'Emil'), ('person_2', 'Anton'), ('person_3', 'Kathrine'), ('person_4', 'Frederikke'), ('person_5', 'Søren'), ('person_6', 'Person 6')], default='person_1', max_length=20, verbose_name='Booker'),
        ),
    ]
