# Generated by Django 5.2.17 on 2026-09-10 11:36

import filarkiv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('category', models.CharField(choices=[('manual', 'Manual'), ('papir', 'Papir'), ('billede', 'Billede'), ('andet', 'Andet')], default='andet', max_length=20, verbose_name='Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivelse')),
                ('file', models.FileField(upload_to=filarkiv.models.archive_upload_path, verbose_name='Fil')),
                ('uploaded_by', models.CharField(blank=True, choices=[('person_1', 'Emil'), ('person_2', 'Anton'), ('person_3', 'Kathrine'), ('person_4', 'Frederikke'), ('person_5', 'Søren'), ('person_6', 'Person 6')], max_length=20, verbose_name='Uploadet af')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadet')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
