# Generated by Django 5.2.17 on 2026-09-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filarkiv', '0002_folder_remove_archivefile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivefile',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
