# Generated by Django 5.2.17 on 2026-09-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivelse')),
                ('status', models.CharField(choices=[('onske', 'Ønskede forbedringer'), ('reparation', 'Nødvendige reparationer'), ('igang', 'Igangværende'), ('faerdig', 'Færdige')], default='onske', max_length=20, verbose_name='Status')),
                ('created_by', models.CharField(blank=True, choices=[('person_1', 'Emil'), ('person_2', 'Anton'), ('person_3', 'Kathrine'), ('person_4', 'Frederikke'), ('person_5', 'Søren'), ('person_6', 'Person 6')], max_length=20, verbose_name='Oprettet af')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Opdateret')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, choices=[('person_1', 'Emil'), ('person_2', 'Anton'), ('person_3', 'Kathrine'), ('person_4', 'Frederikke'), ('person_5', 'Søren'), ('person_6', 'Person 6')], max_length=20, verbose_name='Fra')),
                ('text', models.TextField(verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vedligehold.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
